---
roles:
  - { role: geerlingguy.nginx }
#- name: "install nginx"
#  yum: name=nginx state=latest
#- name: "stop nginx and disable starting at boot time"
#  service: name=nginx state=stopped enabled=no
