---
- name: "install nginx"
  yum: name=nginx state=latest
- name: "stop nginx and disable starting at boot time"
  service: name=nginx state=stopped enabled=no

- name: create abtest.dev vhost file
  template:
    src: ../nginx.conf/00-abtest.conf
    dest: /etc/nginx/conf.d/00-abtest.conf

# @TODO disable all not required module and configuring to have better performance
- name: configure nginx to use apache group/user (to make easily working php-fpm with same config)
  lineinfile:
    dest: //etc/nginx/nginx.conf
    regexp: 'user nginx;'
    line: 'user apache;'
    state: present
