---
- name: Install remi repo.
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
    state: present

- name: installing php7.1
  yum: name=php71 state=latest

- name: installing php71-php-fpm
  yum: name=php71-php-fpm state=latest

- name: installing php71-php-bcmath
  yum: name=php71-php-bcmath state=latest

- name: installing php71-php-opcache
  yum: name=php71-php-opcache state=latest

- name: php-fpm max-children setting
  lineinfile:
    dest: /etc/opt/remi/php71/php-fpm.d/www.conf
    regexp: '^pm.max_children = 50'
    line: 'pm.max_children = 1000'
    state: present

#- name: php-fpm pm=static
#  lineinfile:
#    dest:
#    regexp: '^pm = dynamic'
#    line: 'pm = static'
#    state: present

- name: clone php-fpm pool www.conf (httpd 2.4.6 does not support unix socket)
  shell: cp /etc/opt/remi/php71/php-fpm.d/www.conf /etc/opt/remi/php71/php-fpm.d/www.conf.httpd

- name: configure php-fpm for using unix socket
  lineinfile:
    dest: /etc/opt/remi/php71/php-fpm.d/www.conf
    regexp: '^listen = 127.0.0.1:9000'
    line: 'listen = /var/run/php71-php-fpm.socket'
    state: present

- name: configure php-fpm for group
  lineinfile:
    dest: /etc/opt/remi/php71/php-fpm.d/www.conf
    regexp: ';listen.owner = nobody'
    line: 'listen.owner = apache'
    state: present

- name: configure php-fpm for owner
  lineinfile:
    dest: /etc/opt/remi/php71/php-fpm.d/www.conf
    regexp: ';listen.group = nobody'
    line: 'listen.group = apache'
    state: present

- name: clone php-fpm pool www.conf (nginx backup for switching it)
  shell: cp /etc/opt/remi/php71/php-fpm.d/www.conf /etc/opt/remi/php71/php-fpm.d/www.conf.nginx
