---
- name: Add yum repository
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present
    disable_gpg_check: yes
    enablerepo: yes

name: Install remi repo.
     yum:
       name: http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
       state: present
#  yum_repository:
#    name: remi
#    description: REMI Release 7
#    baseurl: http://rpms.remirepo.net/enterprise/remi-release-7
#
#    gpgcheck: no
#    enabled: yes

- name: installing php7.1
  yum: name=php71 state=latest