---
- name: Install remi repo.
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
    state: present

- name: installing php7.1
  yum: name=php71 state=latest

- name: installing php-71-php-fpm
  yum:
