---
- name: Install R packages.
  yum:
    name: R
    state: present

- name: Rscript install.packages('knitr', dependencies = TRUE)
  shell: /usr/bin/Rscript -e "install.packages('knitr', dependencies = TRUE, repos='http://cran.us.r-project.org')"
