---
#- name: Ensuring selinux is enforced
#  selinux: policy=targeted state=enforcing

#semanage port -a -t http_port_t -p tcp 9000
- name: seport 80 allowed to connect 9000
  seport: ports=9000 proto=tcp setype=http_port_t state=present

# Set (httpd_can_network_connect) flag on and keep it persistent across reboots
- name: selinux networn connect bool config
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

 #setsebool -P httpd_read_user_content 1
- name: selinux httpd read user content
  seboolean:
    name: httpd_read_user_content
    state: yes
    persistent: yes

- name: selinux permissive temporary ansible task
  selinux: policy=targeted state=disabled