# Disable SELinux
#- selinux:
#    state: permissive

sebool:
#semanage port -a -t http_port_t -p tcp 9000
- name: seport 80 allowed to connect 9000
  seport: ports=9000 proto=tcp setype=http_port_t state=present

# Set (httpd_can_network_connect) flag on and keep it persistent across reboots
- name:
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes