---
- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^[\S]+\s+swap\s+swap'
    state: absent
  #become: yes

- name: swap - disable swap
  command: swapoff -a
  ignore_errors: yes
  #become: yes
