---
- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap'
    state: absent
  #become: yes

- name: swap - disable swap
  command: swapoff --all
  ignore_errors: yes
  #become: yes
