---
- name: web benchmark apache & nginx machine
  hosts: all
  become: true
  tasks:
    - name: vim
      yum: name=vim state=latest
    - name: htop
      yum: name=htop state=latest
    - include: task/apache.yml
    - include: task/nginx.yml
    - include: task/php.yml
    - include: task/swap.yml

#  handlers:
#    - name: restart apache2
#      service: name=apache2 state=restarted


